# Exported from:        http://host.docker.internal:5516/
# Release version:      23.1.0-412.1104
# Date created:         Wed Apr 12 16:04:12 UTC 2023

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Templates.yaml
  - Connections.yaml
