output "cluster_name" {
  description = "EKS cluster Name."
  value       = module.dev_cluster.cluster_name
}#
output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       =  module.dev_cluster.cluster_endpoint
}
output "project" {
  value   = var.project
}
# output "cluster_security_group_id" {
#   description = "Security group ids attached to the cluster control plane."
#   value       = module.dev_cluster.cluster_security_group_id
# }
#
# output "kubectl_config" {
#   description = "kubectl config as generated by the module."
#   value       = module.dev_cluster.kubeconfig
# }
#
# output "config_map_aws_auth" {
#   description = "A kubernetes configuration to authenticate to this EKS cluster."
#   value       = module.dev_cluster.config_map_aws_auth
# }
#
output "region" {
  description = "AWS region"
  value       = var.region
}
output "password" {
  value   = "passw0rd"
}
output "dbname" {
  value   = "petclinic"
}
output "user" {
  value   = "petclinic"
}
output "db_profile" {
  value   = "default"
}
output "PETCLINIC_URL" {
  value   = "petclinic.192.168.17.11.xip.io"
}
