# Exported from:        http://host.docker.internal:5516/
# Release version:      23.1.0-406.1500
# Date created:         Mon Apr 10 18:32:43 UTC 2023

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Templates.yaml
