# Exported from:        http://LAPTOP-E5FJSD06:5517/
# Release version:      23.1.0-405.913
# Date created:         Thu Apr 06 12:18:03 IST 2023

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Templates.yaml
