# Exported from:        http://localhost:5516/
# Release version:      23.1.0-beta.10
# Date created:         Mon Apr 03 10:39:56 UTC 2023

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Templates.yaml
