
apiVersion: xl-release/v1
kind: Release
spec:
  name: Trigger Continuous Delivery
  template: github/Continuous Delivery
  variables:
    ARGO_APP_NAME: "helloworld-dev"
    GIT_REPO_URL: "https://github.com/isaacsatish/howto.git"
    GIT_REPO_NAME: "howto"   
    LOCAL_GIT_CLONE_PATH: "/home/ubuntu/git-temp-dir"
    MANIFEST_PATH_IN_GIT: "argocd/helloworld-cd/dev"
    MANIFEST_FILE: "helloworld.yaml"
    NEW_TAG: PLACEHOLDER

